### PR TITLE
Keep track or rounds and client_ids

### PR DESCRIPTION
**Pull request by udameli**
This PR updates the data selection for testing and validation to avoid reusing samples across clients. Additionally, it also prevents sample reuse across training rounds.

There's a bug where client_id get overwritten by the last known client id in MNIST model trainer. I will fix it in the next PR.

### CODE REVIEW

**Comment by eyp** [comment]
First of all, thank you for your contributions. I didn't expect anyone working on this repo.

**Comment by udameli** [comment]
Hi @eyp, so sorry I didn't realize I pushed a PR to your repo. I thought I pushed it to my fork hence the silly log messages.
 
There are some rough edges in my code though. Until I fix them, please feel free to revert the PR if you prefer. I'll let you know when the fix is ready 🙏

**Comment by eyp** [comment]
I'm sorry, don't get me wrong, I'm pretty happy you contributed. As I said you already fixed those logs, that in any case are minor things. 
The project has quite room for adding lot of features, but I've never had the motivation to work on it alone.
As I said, I'm not so picky to revert any of your changes.

Thanks again.

**Comment by udameli** [comment]
Thank you! Happy to contribute. I will push a more robust of client id and round tracking in the next week or so :)

**Pull request merged**
